name: SMP-ACTION-NEW
on:
  push:
    branches:
      - 'master'

jobs:
  job1:
    name: everything
    runs-on: ubuntu-latest
    steps:
      - name: mesheryctl action
        uses: s1ntaxe770r/mesheryctl-actions@main
      - name: Do stuff
        # any command that mesheryctl is capable of handling
        run: |
          mesheryctl perf apply --profile test --url https://google.com -t ~/auth.json
