# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install mesheryctl
        run: curl -L https://git.io/meshery | bash -
      - name: verify install
        run: mesheryctl version
        
      - name: install go
        run: apt install golang-go
        
      - name: install kind
        run: GO111MODULE="on" go get sigs.k8s.io/kind@v0.10.0 && kind create cluster
        
      - name: export kubeconfig
        run: export KUBECONFIG=${HOME}/.kube/config
        
      - name: install helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        
      - name: deploy meshery
        run: |
             git clone https://github.com/layer5io/meshery.git; cd meshery
             kubectl create namespace meshery
             helm install meshery --namespace meshery install/kubernetes/helm/meshery
 
